// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1ks-0pyMZeQtSV5UA-CDtaWuSZnv8YKM',
    appId: '1:224317925232:web:106a9ab73c862a0766d1b5',
    messagingSenderId: '224317925232',
    projectId: 'cookbook-a58ba',
    authDomain: 'cookbook-a58ba.firebaseapp.com',
    storageBucket: 'cookbook-a58ba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZkiTs4qxHaIxkhl5yyEGNQyiHJnSVFDA',
    appId: '1:224317925232:android:9fe563c77c33714566d1b5',
    messagingSenderId: '224317925232',
    projectId: 'cookbook-a58ba',
    storageBucket: 'cookbook-a58ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAodkH8-mM_eRw93m5m-eG3NTI8tCLdL6s',
    appId: '1:224317925232:ios:82ae0308a136122e66d1b5',
    messagingSenderId: '224317925232',
    projectId: 'cookbook-a58ba',
    storageBucket: 'cookbook-a58ba.firebasestorage.app',
    iosBundleId: 'com.example.cookbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAodkH8-mM_eRw93m5m-eG3NTI8tCLdL6s',
    appId: '1:224317925232:ios:82ae0308a136122e66d1b5',
    messagingSenderId: '224317925232',
    projectId: 'cookbook-a58ba',
    storageBucket: 'cookbook-a58ba.firebasestorage.app',
    iosBundleId: 'com.example.cookbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1ks-0pyMZeQtSV5UA-CDtaWuSZnv8YKM',
    appId: '1:224317925232:web:eb858b329582ef5b66d1b5',
    messagingSenderId: '224317925232',
    projectId: 'cookbook-a58ba',
    authDomain: 'cookbook-a58ba.firebaseapp.com',
    storageBucket: 'cookbook-a58ba.firebasestorage.app',
  );
}
